### ISSUE TITLE
Write a Python SDK for merchants

### ISSUE THREAD

**Issue by alranel** [italia/18app-python-example#1]
The documentation, test files and a description of the test environment are available here:

[Progetto18app.zip](https://github.com/italia/18app-dotnet-sdk/files/1356869/Progetto18app.zip)
[WS_VerificaVoucher.zip](https://github.com/italia/18app-dotnet-sdk/files/1356870/WS_VerificaVoucher.zip)
[Linee Guida Esercenti_ottobre 2016.pdf](https://github.com/italia/18app-dotnet-sdk/files/1356867/Linee.Guida.Esercenti_ottobre.2016.pdf)

Qui spiegazioni su 18app: https://developers.italia.it/it/18app/

**Comment by gtico80** [comment]
Pull request https://github.com/italia/18app-python-sdk/pull/3/commits/833cb1eb8f8536109db28ee0732f3ae3dbdb89b3
